### ISSUE TITLE
Any way to convert from CoNLL format to ROSTER?

### ISSUE THREAD

**Issue by mrm8488** [yumeng5/RoSTER#1]

**Comment by yumeng5** [comment]
Hi @mrm8488 ,

If your data are in CoNLL format, you could modify the [`read_file`](https://github.com/yumeng5/RoSTER/blob/bdbba2df3868d85f55e59958bb04b45f7a668ac6/src/utils.py#L15) function to read tokens and labels from CoNLL format files instead of the assumed file format in RoSTER.

Best,
Yu
