### ISSUE TITLE
How to get the concrete prediction results on the test data

### ISSUE THREAD

**Issue by Moonlightxb** [yumeng5/RoSTER#2]
Good work！But how to use the trained model to get the concrete prediction results on the test data

**Comment by yumeng5** [comment]
Hi @Moonlightxb ,

I believe you could directly obtain the model predictions as `y_pred` [here](https://github.com/yumeng5/RoSTER/blob/bdbba2df3868d85f55e59958bb04b45f7a668ac6/src/train.py#L145).

Best,
Yu
